language: node_js

services: 
  - docker

node_js: 
  - "9"

sudo: enabled

os: ubuntu

before_install:
  - npm install codecov -g
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install -g mocha


env:
  - TEST_DIR=angular-client
  - TEST_DIR=express-server

script:
  - 
  - cd $TEST_DIR && npm install && npm test


cache:
  directories:
    - "angular-client/node_modules"
    - "express-server/node_modules"

